// Generated by https://quicktype.io

export interface CreatePublication {
  title: string;
  description: string;
  content: string;
  reference_link: string;
  cities_id: number;
  publications_types_id: number;
  tags: number[];
}
