// Generated by https://quicktype.io

export interface PublicationsResponse {
  results: Publications;
}

export interface Publications {
  count: number;
  totalPages: number;
  CurrentPage: number;
  results: Publication[];
}

export interface Publication {
  id: string;
  title: string;
  description: string;
  content: string;
  reference_link: string;
  cities_id: string;
  user_id: string;
  publications_types_id: string;
  votes_count: number;
  user: User;
  images: Array<Image | null>;
}

export interface Image {
  image_url: string;
  order: number;
}

export interface User {
  id: string;
  first_name: string;
  last_name: string;
  country_id: null;
  image_url: null | string;
}
