// Generated by https://quicktype.io

export interface UserVotesResponse {
  results: UserVotes;
}

export interface UserVotes {
  count: number;
  totalPages: number;
  CurrentPage: number;
  results: Votes[];
}

export interface Votes {
  user_id: string;
  publications_id: string;
}
