// Generated by https://quicktype.io

export interface UserVotesResponse {
  results: Results;
}

export interface Results {
  count: number;
  totalPages: number;
  CurrentPage: number;
  results: Result[];
}

export interface Result {
  id: string;
  title: string;
  description: string;
  content: string;
  reference_link: string;
  cities_id: string;
  user_id: string;
  publications_types_id: string;
  created_at: string;
  updated_at: string;
  images: Image[];
}

export interface Image {
  image_url: string;
  order: number;
}
