// Generated by https://quicktype.io

export interface PublicationTypesResponse {
  count: number;
  rows: PublicationType[];
}

export interface PublicationType {
  id: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
}
