// Generated by https://quicktype.io

export interface ProfileResponse {
  results: Results;
}

export interface Results {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  username: string;
  image_url: null;
  profiles: Profile[];
}

export interface Profile {
  id: string;
  user_id: string;
  role_id: number;
  created_at: string;
  updated_at: string;
}

// Generated by https://quicktype.io

export interface ProfileDetailsResponse {
  result: Result;
  interests: Interest[];
}

export interface Interest {
  tag_id: number;
  user_id: string;
  tags: Tags;
}

export interface Tags {
  id: number;
  name: string;
}

export interface Result {
  id: string;
  code_phone: string;
  country_id: string;
  first_name: string;
  last_name: string;
  username: string;
  image_url: string;
  email: string;
  interests: Interest[];
  phone: string;
}
