// Generated by https://quicktype.io

export interface ProfileResponse {
  results: Results;
}

export interface Results {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  username: string;
  image_url: null;
  profiles: Profile[];
}

export interface Profile {
  id: string;
  user_id: string;
  role_id: number;
  created_at: string;
  updated_at: string;
}
